package by.tishalovichm.grpc;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PokemonService.proto

// Protobuf Java Version: 3.25.1
public final class PokemonServiceOuterClass {
  private PokemonServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code PokemonType}
   */
  public enum PokemonType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NORMAL = 0;</code>
     */
    NORMAL(0),
    /**
     * <code>FIRE = 1;</code>
     */
    FIRE(1),
    /**
     * <code>WATER = 2;</code>
     */
    WATER(2),
    /**
     * <code>ELECTRIC = 3;</code>
     */
    ELECTRIC(3),
    /**
     * <code>GRASS = 4;</code>
     */
    GRASS(4),
    /**
     * <code>ICE = 5;</code>
     */
    ICE(5),
    /**
     * <code>FIGHTING = 6;</code>
     */
    FIGHTING(6),
    /**
     * <code>POISON = 7;</code>
     */
    POISON(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NORMAL = 0;</code>
     */
    public static final int NORMAL_VALUE = 0;
    /**
     * <code>FIRE = 1;</code>
     */
    public static final int FIRE_VALUE = 1;
    /**
     * <code>WATER = 2;</code>
     */
    public static final int WATER_VALUE = 2;
    /**
     * <code>ELECTRIC = 3;</code>
     */
    public static final int ELECTRIC_VALUE = 3;
    /**
     * <code>GRASS = 4;</code>
     */
    public static final int GRASS_VALUE = 4;
    /**
     * <code>ICE = 5;</code>
     */
    public static final int ICE_VALUE = 5;
    /**
     * <code>FIGHTING = 6;</code>
     */
    public static final int FIGHTING_VALUE = 6;
    /**
     * <code>POISON = 7;</code>
     */
    public static final int POISON_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static PokemonType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static PokemonType forNumber(int value) {
      switch (value) {
        case 0: return NORMAL;
        case 1: return FIRE;
        case 2: return WATER;
        case 3: return ELECTRIC;
        case 4: return GRASS;
        case 5: return ICE;
        case 6: return FIGHTING;
        case 7: return POISON;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PokemonType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PokemonType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PokemonType>() {
            public PokemonType findValueByNumber(int number) {
              return PokemonType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return PokemonServiceOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final PokemonType[] VALUES = values();

    public static PokemonType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PokemonType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PokemonType)
  }

  public interface PokemonRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PokemonRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string pokemonName = 1;</code>
     * @return The pokemonName.
     */
    String getPokemonName();
    /**
     * <code>string pokemonName = 1;</code>
     * @return The bytes for pokemonName.
     */
    com.google.protobuf.ByteString
        getPokemonNameBytes();
  }
  /**
   * Protobuf type {@code PokemonRequest}
   */
  public static final class PokemonRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PokemonRequest)
      PokemonRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PokemonRequest.newBuilder() to construct.
    private PokemonRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PokemonRequest() {
      pokemonName_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new PokemonRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PokemonServiceOuterClass.internal_static_PokemonRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PokemonServiceOuterClass.internal_static_PokemonRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PokemonRequest.class, Builder.class);
    }

    public static final int POKEMONNAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object pokemonName_ = "";
    /**
     * <code>string pokemonName = 1;</code>
     * @return The pokemonName.
     */
    @Override
    public String getPokemonName() {
      Object ref = pokemonName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        pokemonName_ = s;
        return s;
      }
    }
    /**
     * <code>string pokemonName = 1;</code>
     * @return The bytes for pokemonName.
     */
    @Override
    public com.google.protobuf.ByteString
        getPokemonNameBytes() {
      Object ref = pokemonName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pokemonName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pokemonName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pokemonName_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pokemonName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, pokemonName_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PokemonRequest)) {
        return super.equals(obj);
      }
      PokemonRequest other = (PokemonRequest) obj;

      if (!getPokemonName()
          .equals(other.getPokemonName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + POKEMONNAME_FIELD_NUMBER;
      hash = (53 * hash) + getPokemonName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PokemonRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PokemonRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PokemonRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PokemonRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PokemonRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PokemonRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PokemonRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PokemonRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static PokemonRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static PokemonRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PokemonRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PokemonRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PokemonRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PokemonRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PokemonRequest)
        PokemonRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PokemonServiceOuterClass.internal_static_PokemonRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PokemonServiceOuterClass.internal_static_PokemonRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PokemonRequest.class, Builder.class);
      }

      // Construct using PokemonServiceOuterClass.PokemonRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        pokemonName_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PokemonServiceOuterClass.internal_static_PokemonRequest_descriptor;
      }

      @Override
      public PokemonRequest getDefaultInstanceForType() {
        return PokemonRequest.getDefaultInstance();
      }

      @Override
      public PokemonRequest build() {
        PokemonRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public PokemonRequest buildPartial() {
        PokemonRequest result = new PokemonRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(PokemonRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.pokemonName_ = pokemonName_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PokemonRequest) {
          return mergeFrom((PokemonRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PokemonRequest other) {
        if (other == PokemonRequest.getDefaultInstance()) return this;
        if (!other.getPokemonName().isEmpty()) {
          pokemonName_ = other.pokemonName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                pokemonName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object pokemonName_ = "";
      /**
       * <code>string pokemonName = 1;</code>
       * @return The pokemonName.
       */
      public String getPokemonName() {
        Object ref = pokemonName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          pokemonName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string pokemonName = 1;</code>
       * @return The bytes for pokemonName.
       */
      public com.google.protobuf.ByteString
          getPokemonNameBytes() {
        Object ref = pokemonName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          pokemonName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pokemonName = 1;</code>
       * @param value The pokemonName to set.
       * @return This builder for chaining.
       */
      public Builder setPokemonName(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        pokemonName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string pokemonName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPokemonName() {
        pokemonName_ = getDefaultInstance().getPokemonName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string pokemonName = 1;</code>
       * @param value The bytes for pokemonName to set.
       * @return This builder for chaining.
       */
      public Builder setPokemonNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        pokemonName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PokemonRequest)
    }

    // @@protoc_insertion_point(class_scope:PokemonRequest)
    private static final PokemonRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PokemonRequest();
    }

    public static PokemonRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PokemonRequest>
        PARSER = new com.google.protobuf.AbstractParser<PokemonRequest>() {
      @Override
      public PokemonRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PokemonRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PokemonRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public PokemonRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PokemonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Pokemon)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 health = 2;</code>
     * @return The health.
     */
    int getHealth();

    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    String getDescription();
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>repeated .PokemonType types = 4;</code>
     * @return A list containing the types.
     */
    java.util.List<PokemonType> getTypesList();
    /**
     * <code>repeated .PokemonType types = 4;</code>
     * @return The count of types.
     */
    int getTypesCount();
    /**
     * <code>repeated .PokemonType types = 4;</code>
     * @param index The index of the element to return.
     * @return The types at the given index.
     */
    PokemonType getTypes(int index);
    /**
     * <code>repeated .PokemonType types = 4;</code>
     * @return A list containing the enum numeric values on the wire for types.
     */
    java.util.List<Integer>
    getTypesValueList();
    /**
     * <code>repeated .PokemonType types = 4;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of types at the given index.
     */
    int getTypesValue(int index);
  }
  /**
   * Protobuf type {@code Pokemon}
   */
  public static final class Pokemon extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Pokemon)
      PokemonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Pokemon.newBuilder() to construct.
    private Pokemon(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Pokemon() {
      name_ = "";
      description_ = "";
      types_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Pokemon();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PokemonServiceOuterClass.internal_static_Pokemon_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PokemonServiceOuterClass.internal_static_Pokemon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Pokemon.class, Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEALTH_FIELD_NUMBER = 2;
    private int health_ = 0;
    /**
     * <code>int32 health = 2;</code>
     * @return The health.
     */
    @Override
    public int getHealth() {
      return health_;
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile Object description_ = "";
    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    @Override
    public String getDescription() {
      Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    @Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPES_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private java.util.List<Integer> types_;
    private static final com.google.protobuf.Internal.ListAdapter.Converter<
        Integer, PokemonType> types_converter_ =
            new com.google.protobuf.Internal.ListAdapter.Converter<
                Integer, PokemonType>() {
              public PokemonType convert(Integer from) {
                PokemonType result = PokemonType.forNumber(from);
                return result == null ? PokemonType.UNRECOGNIZED : result;
              }
            };
    /**
     * <code>repeated .PokemonType types = 4;</code>
     * @return A list containing the types.
     */
    @Override
    public java.util.List<PokemonType> getTypesList() {
      return new com.google.protobuf.Internal.ListAdapter<
          Integer, PokemonType>(types_, types_converter_);
    }
    /**
     * <code>repeated .PokemonType types = 4;</code>
     * @return The count of types.
     */
    @Override
    public int getTypesCount() {
      return types_.size();
    }
    /**
     * <code>repeated .PokemonType types = 4;</code>
     * @param index The index of the element to return.
     * @return The types at the given index.
     */
    @Override
    public PokemonType getTypes(int index) {
      return types_converter_.convert(types_.get(index));
    }
    /**
     * <code>repeated .PokemonType types = 4;</code>
     * @return A list containing the enum numeric values on the wire for types.
     */
    @Override
    public java.util.List<Integer>
    getTypesValueList() {
      return types_;
    }
    /**
     * <code>repeated .PokemonType types = 4;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of types at the given index.
     */
    @Override
    public int getTypesValue(int index) {
      return types_.get(index);
    }
    private int typesMemoizedSerializedSize;

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (health_ != 0) {
        output.writeInt32(2, health_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
      }
      if (getTypesList().size() > 0) {
        output.writeUInt32NoTag(34);
        output.writeUInt32NoTag(typesMemoizedSerializedSize);
      }
      for (int i = 0; i < types_.size(); i++) {
        output.writeEnumNoTag(types_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (health_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, health_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < types_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(types_.get(i));
        }
        size += dataSize;
        if (!getTypesList().isEmpty()) {  size += 1;
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(dataSize);
        }typesMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Pokemon)) {
        return super.equals(obj);
      }
      Pokemon other = (Pokemon) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getHealth()
          != other.getHealth()) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!types_.equals(other.types_)) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + HEALTH_FIELD_NUMBER;
      hash = (53 * hash) + getHealth();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      if (getTypesCount() > 0) {
        hash = (37 * hash) + TYPES_FIELD_NUMBER;
        hash = (53 * hash) + types_.hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Pokemon parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Pokemon parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Pokemon parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Pokemon parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Pokemon parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Pokemon parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Pokemon parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Pokemon parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Pokemon parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Pokemon parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Pokemon parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Pokemon parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Pokemon prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Pokemon}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Pokemon)
        PokemonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PokemonServiceOuterClass.internal_static_Pokemon_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PokemonServiceOuterClass.internal_static_Pokemon_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Pokemon.class, Builder.class);
      }

      // Construct using PokemonServiceOuterClass.Pokemon.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        health_ = 0;
        description_ = "";
        types_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PokemonServiceOuterClass.internal_static_Pokemon_descriptor;
      }

      @Override
      public Pokemon getDefaultInstanceForType() {
        return Pokemon.getDefaultInstance();
      }

      @Override
      public Pokemon build() {
        Pokemon result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Pokemon buildPartial() {
        Pokemon result = new Pokemon(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(Pokemon result) {
        if (((bitField0_ & 0x00000008) != 0)) {
          types_ = java.util.Collections.unmodifiableList(types_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.types_ = types_;
      }

      private void buildPartial0(Pokemon result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.health_ = health_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.description_ = description_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Pokemon) {
          return mergeFrom((Pokemon)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Pokemon other) {
        if (other == Pokemon.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getHealth() != 0) {
          setHealth(other.getHealth());
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.types_.isEmpty()) {
          if (types_.isEmpty()) {
            types_ = other.types_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureTypesIsMutable();
            types_.addAll(other.types_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                health_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                description_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                int tmpRaw = input.readEnum();
                ensureTypesIsMutable();
                types_.add(tmpRaw);
                break;
              } // case 32
              case 34: {
                int length = input.readRawVarint32();
                int oldLimit = input.pushLimit(length);
                while(input.getBytesUntilLimit() > 0) {
                  int tmpRaw = input.readEnum();
                  ensureTypesIsMutable();
                  types_.add(tmpRaw);
                }
                input.popLimit(oldLimit);
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int health_ ;
      /**
       * <code>int32 health = 2;</code>
       * @return The health.
       */
      @Override
      public int getHealth() {
        return health_;
      }
      /**
       * <code>int32 health = 2;</code>
       * @param value The health to set.
       * @return This builder for chaining.
       */
      public Builder setHealth(int value) {

        health_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 health = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearHealth() {
        bitField0_ = (bitField0_ & ~0x00000002);
        health_ = 0;
        onChanged();
        return this;
      }

      private Object description_ = "";
      /**
       * <code>string description = 3;</code>
       * @return The description.
       */
      public String getDescription() {
        Object ref = description_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        description_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        description_ = getDefaultInstance().getDescription();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        description_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.util.List<Integer> types_ =
        java.util.Collections.emptyList();
      private void ensureTypesIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          types_ = new java.util.ArrayList<Integer>(types_);
          bitField0_ |= 0x00000008;
        }
      }
      /**
       * <code>repeated .PokemonType types = 4;</code>
       * @return A list containing the types.
       */
      public java.util.List<PokemonType> getTypesList() {
        return new com.google.protobuf.Internal.ListAdapter<
            Integer, PokemonType>(types_, types_converter_);
      }
      /**
       * <code>repeated .PokemonType types = 4;</code>
       * @return The count of types.
       */
      public int getTypesCount() {
        return types_.size();
      }
      /**
       * <code>repeated .PokemonType types = 4;</code>
       * @param index The index of the element to return.
       * @return The types at the given index.
       */
      public PokemonType getTypes(int index) {
        return types_converter_.convert(types_.get(index));
      }
      /**
       * <code>repeated .PokemonType types = 4;</code>
       * @param index The index to set the value at.
       * @param value The types to set.
       * @return This builder for chaining.
       */
      public Builder setTypes(
          int index, PokemonType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTypesIsMutable();
        types_.set(index, value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .PokemonType types = 4;</code>
       * @param value The types to add.
       * @return This builder for chaining.
       */
      public Builder addTypes(PokemonType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTypesIsMutable();
        types_.add(value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .PokemonType types = 4;</code>
       * @param values The types to add.
       * @return This builder for chaining.
       */
      public Builder addAllTypes(
          Iterable<? extends PokemonType> values) {
        ensureTypesIsMutable();
        for (PokemonType value : values) {
          types_.add(value.getNumber());
        }
        onChanged();
        return this;
      }
      /**
       * <code>repeated .PokemonType types = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTypes() {
        types_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .PokemonType types = 4;</code>
       * @return A list containing the enum numeric values on the wire for types.
       */
      public java.util.List<Integer>
      getTypesValueList() {
        return java.util.Collections.unmodifiableList(types_);
      }
      /**
       * <code>repeated .PokemonType types = 4;</code>
       * @param index The index of the value to return.
       * @return The enum numeric value on the wire of types at the given index.
       */
      public int getTypesValue(int index) {
        return types_.get(index);
      }
      /**
       * <code>repeated .PokemonType types = 4;</code>
       * @param index The index to set the value at.
       * @param value The enum numeric value on the wire for types to set.
       * @return This builder for chaining.
       */
      public Builder setTypesValue(
          int index, int value) {
        ensureTypesIsMutable();
        types_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .PokemonType types = 4;</code>
       * @param value The enum numeric value on the wire for types to add.
       * @return This builder for chaining.
       */
      public Builder addTypesValue(int value) {
        ensureTypesIsMutable();
        types_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .PokemonType types = 4;</code>
       * @param values The enum numeric values on the wire for types to add.
       * @return This builder for chaining.
       */
      public Builder addAllTypesValue(
          Iterable<Integer> values) {
        ensureTypesIsMutable();
        for (int value : values) {
          types_.add(value);
        }
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Pokemon)
    }

    // @@protoc_insertion_point(class_scope:Pokemon)
    private static final Pokemon DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Pokemon();
    }

    public static Pokemon getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Pokemon>
        PARSER = new com.google.protobuf.AbstractParser<Pokemon>() {
      @Override
      public Pokemon parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Pokemon> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Pokemon> getParserForType() {
      return PARSER;
    }

    @Override
    public Pokemon getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PokemonResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PokemonResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .Pokemon pokemon = 2;</code>
     * @return Whether the pokemon field is set.
     */
    boolean hasPokemon();
    /**
     * <code>optional .Pokemon pokemon = 2;</code>
     * @return The pokemon.
     */
    Pokemon getPokemon();
    /**
     * <code>optional .Pokemon pokemon = 2;</code>
     */
    PokemonOrBuilder getPokemonOrBuilder();
  }
  /**
   * Protobuf type {@code PokemonResponse}
   */
  public static final class PokemonResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PokemonResponse)
      PokemonResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PokemonResponse.newBuilder() to construct.
    private PokemonResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PokemonResponse() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new PokemonResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PokemonServiceOuterClass.internal_static_PokemonResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PokemonServiceOuterClass.internal_static_PokemonResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PokemonResponse.class, Builder.class);
    }

    private int bitField0_;
    public static final int POKEMON_FIELD_NUMBER = 2;
    private Pokemon pokemon_;
    /**
     * <code>optional .Pokemon pokemon = 2;</code>
     * @return Whether the pokemon field is set.
     */
    @Override
    public boolean hasPokemon() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .Pokemon pokemon = 2;</code>
     * @return The pokemon.
     */
    @Override
    public Pokemon getPokemon() {
      return pokemon_ == null ? Pokemon.getDefaultInstance() : pokemon_;
    }
    /**
     * <code>optional .Pokemon pokemon = 2;</code>
     */
    @Override
    public PokemonOrBuilder getPokemonOrBuilder() {
      return pokemon_ == null ? Pokemon.getDefaultInstance() : pokemon_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getPokemon());
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPokemon());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PokemonResponse)) {
        return super.equals(obj);
      }
      PokemonResponse other = (PokemonResponse) obj;

      if (hasPokemon() != other.hasPokemon()) return false;
      if (hasPokemon()) {
        if (!getPokemon()
            .equals(other.getPokemon())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPokemon()) {
        hash = (37 * hash) + POKEMON_FIELD_NUMBER;
        hash = (53 * hash) + getPokemon().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PokemonResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PokemonResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PokemonResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PokemonResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PokemonResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PokemonResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PokemonResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PokemonResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static PokemonResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static PokemonResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PokemonResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PokemonResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PokemonResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PokemonResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PokemonResponse)
        PokemonResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PokemonServiceOuterClass.internal_static_PokemonResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PokemonServiceOuterClass.internal_static_PokemonResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PokemonResponse.class, Builder.class);
      }

      // Construct using PokemonServiceOuterClass.PokemonResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPokemonFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        pokemon_ = null;
        if (pokemonBuilder_ != null) {
          pokemonBuilder_.dispose();
          pokemonBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PokemonServiceOuterClass.internal_static_PokemonResponse_descriptor;
      }

      @Override
      public PokemonResponse getDefaultInstanceForType() {
        return PokemonResponse.getDefaultInstance();
      }

      @Override
      public PokemonResponse build() {
        PokemonResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public PokemonResponse buildPartial() {
        PokemonResponse result = new PokemonResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(PokemonResponse result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.pokemon_ = pokemonBuilder_ == null
              ? pokemon_
              : pokemonBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PokemonResponse) {
          return mergeFrom((PokemonResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PokemonResponse other) {
        if (other == PokemonResponse.getDefaultInstance()) return this;
        if (other.hasPokemon()) {
          mergePokemon(other.getPokemon());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 18: {
                input.readMessage(
                    getPokemonFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Pokemon pokemon_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Pokemon, Pokemon.Builder, PokemonOrBuilder> pokemonBuilder_;
      /**
       * <code>optional .Pokemon pokemon = 2;</code>
       * @return Whether the pokemon field is set.
       */
      public boolean hasPokemon() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .Pokemon pokemon = 2;</code>
       * @return The pokemon.
       */
      public Pokemon getPokemon() {
        if (pokemonBuilder_ == null) {
          return pokemon_ == null ? Pokemon.getDefaultInstance() : pokemon_;
        } else {
          return pokemonBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Pokemon pokemon = 2;</code>
       */
      public Builder setPokemon(Pokemon value) {
        if (pokemonBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pokemon_ = value;
        } else {
          pokemonBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Pokemon pokemon = 2;</code>
       */
      public Builder setPokemon(
          Pokemon.Builder builderForValue) {
        if (pokemonBuilder_ == null) {
          pokemon_ = builderForValue.build();
        } else {
          pokemonBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Pokemon pokemon = 2;</code>
       */
      public Builder mergePokemon(Pokemon value) {
        if (pokemonBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            pokemon_ != null &&
            pokemon_ != Pokemon.getDefaultInstance()) {
            getPokemonBuilder().mergeFrom(value);
          } else {
            pokemon_ = value;
          }
        } else {
          pokemonBuilder_.mergeFrom(value);
        }
        if (pokemon_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .Pokemon pokemon = 2;</code>
       */
      public Builder clearPokemon() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pokemon_ = null;
        if (pokemonBuilder_ != null) {
          pokemonBuilder_.dispose();
          pokemonBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .Pokemon pokemon = 2;</code>
       */
      public Pokemon.Builder getPokemonBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPokemonFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Pokemon pokemon = 2;</code>
       */
      public PokemonOrBuilder getPokemonOrBuilder() {
        if (pokemonBuilder_ != null) {
          return pokemonBuilder_.getMessageOrBuilder();
        } else {
          return pokemon_ == null ?
              Pokemon.getDefaultInstance() : pokemon_;
        }
      }
      /**
       * <code>optional .Pokemon pokemon = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Pokemon, Pokemon.Builder, PokemonOrBuilder>
          getPokemonFieldBuilder() {
        if (pokemonBuilder_ == null) {
          pokemonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Pokemon, Pokemon.Builder, PokemonOrBuilder>(
                  getPokemon(),
                  getParentForChildren(),
                  isClean());
          pokemon_ = null;
        }
        return pokemonBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PokemonResponse)
    }

    // @@protoc_insertion_point(class_scope:PokemonResponse)
    private static final PokemonResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PokemonResponse();
    }

    public static PokemonResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PokemonResponse>
        PARSER = new com.google.protobuf.AbstractParser<PokemonResponse>() {
      @Override
      public PokemonResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PokemonResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PokemonResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public PokemonResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PokemonRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PokemonRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Pokemon_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Pokemon_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PokemonResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PokemonResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024PokemonService.proto\"%\n\016PokemonRequest" +
      "\022\023\n\013pokemonName\030\001 \001(\t\"Y\n\007Pokemon\022\014\n\004name" +
      "\030\001 \001(\t\022\016\n\006health\030\002 \001(\005\022\023\n\013description\030\003 " +
      "\001(\t\022\033\n\005types\030\004 \003(\0162\014.PokemonType\"=\n\017Poke" +
      "monResponse\022\036\n\007pokemon\030\002 \001(\0132\010.PokemonH\000" +
      "\210\001\001B\n\n\010_pokemon*j\n\013PokemonType\022\n\n\006NORMAL" +
      "\020\000\022\010\n\004FIRE\020\001\022\t\n\005WATER\020\002\022\014\n\010ELECTRIC\020\003\022\t\n" +
      "\005GRASS\020\004\022\007\n\003ICE\020\005\022\014\n\010FIGHTING\020\006\022\n\n\006POISO" +
      "N\020\0072C\n\016PokemonService\0221\n\nGetPokemon\022\017.Po" +
      "kemonRequest\032\020.PokemonResponse\"\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PokemonRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PokemonRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PokemonRequest_descriptor,
        new String[] { "PokemonName", });
    internal_static_Pokemon_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Pokemon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Pokemon_descriptor,
        new String[] { "Name", "Health", "Description", "Types", });
    internal_static_PokemonResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PokemonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PokemonResponse_descriptor,
        new String[] { "Pokemon", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
